#############################################################
# Copyright (C) The c-ci project and its contributors
# SPDX-License-Identifier: MIT
#
# Makefile for building citest.exe with MingW32 (GCC-3.2)
# Use: make -f Makefile.m32 GTEST_ROOT=....
#
########################################################
CXX = g++
CC = gcc
LD = g++

ifeq "$(GTEST_ROOT)" ""
  $(error missing GTEST_ROOT)
endif

# Where to find the c-ci source code; needed because the tests use library-internal headers
CI_SRC_DIR = ..
# Where to find the built c-ci static library
CI_BLD_DIR = ..
CILIB = $(CI_BLD_DIR)/src/lib/libcci.a
CPPFLAGS = -I$(CI_SRC_DIR)/include -I$(CI_SRC_DIR)/src/lib -I$(CI_SRC_DIR)/src/lib/include -I$(GTEST_ROOT)/include -DCI_STATICLIB -DCI_NO_DEPRECATED
CXXFLAGS = -Wall $(PTHREAD_CFLAGS) -std=gnu++14
LDFLAGS =
LDLIBS = -lws2_32 -liphlpapi

# Makefile.inc provides the TESTSOURCES and TESTHEADERS defines
include Makefile.inc

OBJS := $(patsubst %.cc,%.o,$(strip $(TESTSOURCES)))
FUZZOBJS := $(patsubst %.c,%.o,$(strip $(FUZZSOURCES)))
FUZZNAMEOBJS := $(patsubst %.c,%.o,$(strip $(FUZZNAMESOURCES)))
DNSDUMPOBJS := $(patsubst %.cc,%.o,$(strip $(DUMPSOURCES)))

all: citest.exe cifuzz.exe cifuzzname.exe dnsdump.exe

citest.exe: $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(CI_BLD_DIR)/src/lib -lcci $(LDLIBS) -L$(GTEST_ROOT)/lib -lgmock -lgtest

cifuzz.exe: $(FUZZOBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(CI_BLD_DIR)/src/lib -lcci $(LDLIBS)

cifuzzname.exe: $(FUZZNAMEOBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(CI_BLD_DIR)/src/lib -lcci $(LDLIBS)

dnsdump.exe: $(DNSDUMPOBJS)
	$(LD) $(LDFLAGS) -o $@ $^  -L$(CI_BLD_DIR)/src/lib -lcci $(LDLIBS)

$(OBJS): $(TESTHEADERS)

.cc.o:
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -c $<
.c.o:
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $<

test: citest.exe
	./citest.exe --gtest_filter=-*LiveSearchTXT*:*LiveSearchANY*:*LiveGetLocalhostByAddr*
vtest: citest.exe
	./citest.exe -v --gtest_filter=-*LiveSearchTXT*:*LiveSearchANY*:*LiveGetLocalhostByAddr*

clean:
	$(RM) $(OBJS) citest.exe cifuzz.exe cifuzzname.exe dnsdump.exe


