#!/bin/sh
# Copyright (C) The c-ci project and its contributors
# SPDX-License-Identifier: MIT

echo "*** Do not use buildconf. Instead, just use: autoreconf -fi" >&2
exec ${AUTORECONF:-autoreconf} -fi "${@}"
