# Copyright (C) Daniel Stenberg
# SPDX-License-Identifier: MIT
AUTOMAKE_OPTIONS = foreign nostdinc 1.9.6
ACLOCAL_AMFLAGS = -I m4 --install

# what headers to install on 'make install':
include_HEADERS = ci.h ci_version.h ci_build.h ci_dns.h ci_dns_record.h ci_nameser.h

EXTRA_DIST = ci_build.h.cmake ci_build.h.in ci_build.h.dist CMakeLists.txt
