.\"
.\" Copyright 1998 by the Massachusetts Institute of Technology.
.\" SPDX-License-Identifier: MIT
.\"
.TH CI_PARSE_URI_REPLY 3 "14 August 2020"
.SH NAME
ci_parse_uri_reply \- Parse a reply to a DNS query of type URI
.SH SYNOPSIS
.nf
#include <ci.h>

int ci_parse_uri_reply(const unsigned char* \fIabuf\fP, int \fIalen\fP,
                         struct ci_uri_reply** \fIuri_out\fP);
.fi
.SH DESCRIPTION
The \fIci_parse_uri_reply(3)\fP function parses the response to a query of
type URI into a linked list of
.I struct ci_uri_reply 
The parameters
.I abuf
and
.I alen
give the contents of the response.  The result is stored in allocated
memory and a pointer to it stored into the variable pointed to by
.IR uri_out .
It is the caller's responsibility to free the resulting
.IR uri_out
structure when it is no longer needed using the function
\fBci_free_data(3)\fP.

The structure 
.I ci_uri_reply
contains the following fields:
.nf
struct ci_uri_reply {
    struct ci_uri_reply       *next;
    unsigned short              weight;
    unsigned short              priority;
    char                        *uri;
    int                         ttl;
};
.fi
.SH RETURN VALUES
.B ci_parse_uri_reply
can return any of the following values:
.TP 15
.B CI_SUCCESS
The response was successfully parsed.
.TP 15
.B CI_EBADRESP
The response was malformatted.
.TP 15
.B CI_ENODATA
The response did not contain an answer to the query.
.TP 15
.B CI_ENOMEM
Memory was exhausted.
.SH AVAILABILITY

.SH SEE ALSO
.BR ci_query (3)
.BR ci_free_data (3)
